# Generated by Django 3.2 on 2024-02-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
