# Generated by Django 3.2 on 2024-02-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_social_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.social')),
            ],
        ),
    ]
