# Generated by Django 3.2 on 2024-02-22 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', related_query_name='log', to='customers.social'),
        ),
    ]
